"""add causal_run_history

Revision ID: 2e59b7121ef9
Revises: 81735e680476
Create Date: 2026-08-27 22:45:24.564189

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2e59b7121ef9"
down_revision: str | None = "81735e680476"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "causal_run_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "run_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("panel_start_date", sa.Date(), nullable=False),
        sa.Column("panel_end_date", sa.Date(), nullable=False),
        sa.Column("panel_row_count", sa.Integer(), nullable=False),
        sa.Column("n_treated_rows", sa.Integer(), nullable=False),
        sa.Column("mlflow_run_id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("causal_run_history")
    # ### end Alembic commands ###
