"""add drift columns to causal run history

Revision ID: 6fce59619fd1
Revises: 2e59b7121ef9
Create Date: 2026-08-28 07:36:05.303986

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6fce59619fd1"
down_revision: str | None = "2e59b7121ef9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("causal_run_history", sa.Column("dataset_drift_share", sa.Float(), nullable=True))
    op.add_column(
        "causal_run_history", sa.Column("cate_drift_detected", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("causal_run_history", "cate_drift_detected")
    op.drop_column("causal_run_history", "dataset_drift_share")
    # ### end Alembic commands ###
