"""initial schema

Revision ID: 81735e680476
Revises:
Create Date: 2026-08-26 22:21:41.752913

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "81735e680476"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("steam_appid", sa.Integer(), nullable=False),
        sa.Column("itad_id", sa.String(), nullable=True),
        sa.Column("igdb_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("igdb_id"),
        sa.UniqueConstraint("itad_id"),
        sa.UniqueConstraint("steam_appid"),
    )
    op.create_table(
        "discount_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("store", sa.String(), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("depth_pct", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_id", "store", "start_at", name="uq_discount_events_start"),
    )
    op.create_table(
        "game_metadata",
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("genres", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("platforms", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("aggregated_rating", sa.Float(), nullable=True),
        sa.Column("involved_companies", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.PrimaryKeyConstraint("game_id"),
    )
    op.create_table(
        "ingestion_watermarks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("cursor", sa.String(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "game_id", name="uq_watermark_source_game"),
    )
    op.create_table(
        "player_count_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("observed_date", sa.Date(), nullable=False),
        sa.Column("player_count", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("STEAMCHARTS_BOOTSTRAP", "STEAM_API_POLL", name="player_count_source"),
            nullable=False,
        ),
        sa.Column(
            "granularity",
            sa.Enum("DAILY", "MONTHLY", name="player_count_granularity"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_id", "observed_date", "source", name="uq_player_count_obs"),
    )
    op.create_table(
        "price_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("store", sa.String(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("cut_pct", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_id", "store", "observed_at", name="uq_price_history_obs"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("price_history")
    op.drop_table("player_count_history")
    op.drop_table("ingestion_watermarks")
    op.drop_table("game_metadata")
    op.drop_table("discount_events")
    op.drop_table("games")
    # ### end Alembic commands ###
